import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <div className="container">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1>Next JS에 대하여</h1>

        <ul>
          <li>
            <Link legacyBehavior href="/image-lazy-loading">
              <a>1. Image Lazy Loading</a>
            </Link>
          </li>
        </ul>
      </div>

      <style jsx>{`
        .container {
          display: flex;
          flex-direction: column;
          flex: 1;
          align-items: center;
          width: 100%;
          max-width: 800px;
          min-height: 100vh;
          margin: 0 auto;
        }

        ul {
          width: 100%;
          margin-top: 50px;
        }

        a {
          font-size: 25px;
        }
      `}</style>
    </>
  );
}
